### ISSUE TITLE
Image nabi Ishaq error

### ISSUE THREAD

**Issue by dimasandhk** [Zhirrr/islamic-rest-api-indonesian-v2#1]
https://islamic-api-indonesia.herokuapp.com/api/data/json/kisahnabi (array ke 8) nabi ishaq, image_url nya ngga tersedia
`GET http://1.bp.blogspot.com/-dpOj5gl9oBE/Vn3XtbntpadaI/AAAAAAAABvQ/Enz0bRle2xw/s320/ishaq.png 400 (Bad Request)`

**Comment by Zhirrr** [comment]
Fixed Gan 👍

**Comment by dimasandhk** [comment]
Oke sip makasih bang
